version: "3.9"

services:
  database:
    image: mysql
    container_name: database_ignite
    restart: always
    ports:
      - 3306:3306
    environment:
      - USER_DB=
      - SECRET=
      - DATABASE=rentalx
      - PORT_DATABASE=9999
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - /var/lib/mysql

  app:
    build: .
    image: lulucasalves/rentalx
    container_name: rentalx
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local