version: "3.9"

services:
  database:
    image: mysql
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      - USER_DB=
      - SECRET=
      - DATABASE=rentalx
    volumes:
      - /var/lib/mysql
    network_mode: host
  app:
    build: .
    image: lulucasalves/rentalx
    container_name: rentalx
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local