version: "3.9"

services:
  database:
    image: mysql
    container_name: database_ignite
    restart: always
    ports:
      - 6843:6843
    environment:
      - USER_DB=
      - DATABASE=rentalx
      - PORT_DATABASE=6843
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - /var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: rentalx
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local